// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_-GBenHkpk-5gdR9FAPQH6nPJKYoXn_M',
    appId: '1:35860989224:web:741aaffe34a1245c20bc1d',
    messagingSenderId: '35860989224',
    projectId: 'food-app-54643',
    authDomain: 'food-app-54643.firebaseapp.com',
    storageBucket: 'food-app-54643.appspot.com',
    measurementId: 'G-MTBJM3ZDHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj0Ykk98usK3t9nnNOp1JHU939wlIl60U',
    appId: '1:35860989224:android:36708da9b4e9f75120bc1d',
    messagingSenderId: '35860989224',
    projectId: 'food-app-54643',
    storageBucket: 'food-app-54643.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM4PL5YfBBpWi4rJuw9Gejw_W4HeI2po8',
    appId: '1:35860989224:ios:4782b9e80151a2e820bc1d',
    messagingSenderId: '35860989224',
    projectId: 'food-app-54643',
    storageBucket: 'food-app-54643.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM4PL5YfBBpWi4rJuw9Gejw_W4HeI2po8',
    appId: '1:35860989224:ios:4782b9e80151a2e820bc1d',
    messagingSenderId: '35860989224',
    projectId: 'food-app-54643',
    storageBucket: 'food-app-54643.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_-GBenHkpk-5gdR9FAPQH6nPJKYoXn_M',
    appId: '1:35860989224:web:e8d2f1ac8186d09a20bc1d',
    messagingSenderId: '35860989224',
    projectId: 'food-app-54643',
    authDomain: 'food-app-54643.firebaseapp.com',
    storageBucket: 'food-app-54643.appspot.com',
    measurementId: 'G-0NLCMHBZT1',
  );

}